### ISSUE TITLE
Visualist plugin won't load

### ISSUE THREAD

**Issue by UnkzF** [esc-unil/Visualist#11]
I'm having issues loading Visualist plugin with both LTR(3.10.10) and latest release builds (3.14.16). I've tried installing QGIS both via OSGEO and downloading the the .exe files. Any tips on how to handle it?

Heres the error message:

Couldn't load plugin 'visualist' 

FileNotFoundError: [WinError 2] The system cannot find the file specified. 
Traceback (most recent call last):
  File "D:/Pedro/DOCUME~1/OSGEO4W/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "D:/Pedro/DOCUME~1/OSGEO4W/apps/qgis-ltr/./python\qgis\utils.py", line 784, in _import
    _import_paths[p] = _AddDllDirectory(p)
  File "D:/Pedro/DOCUME~1/OSGEO4W/apps/qgis-ltr/./python\qgis\utils.py", line 731, in _errcheck_zero
    raise ctypes.WinError(ctypes.get_last_error())
FileNotFoundError: [WinError 2] The system cannot find the file specified.

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.10-A Coruña A Coruña, 8b051b9a43 

Python Path:
D:/Pedro/DOCUME~1/OSGEO4W/apps/qgis-ltr/./python
C:/Users/Pedro/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Pedro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Pedro/DOCUME~1/OSGEO4W/apps/qgis-ltr/./python/plugins
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37\Scripts
D:\Pedro\Documents\OSGEO4W\bin\python37.zip
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37\DLLs
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37\lib
D:\Pedro\Documents\OSGEO4W\bin
C:\Users\Pedro\AppData\Roaming\Python\Python37\site-packages
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37\lib\site-packages
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37\lib\site-packages\win32
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37\lib\site-packages\win32\lib
D:\Pedro\DOCUME~1\OSGEO4W\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Pedro/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by qrossy** [comment]
Did you try with QGIS 3.16.1 ? A new version of the plugin is in progress for QGis 3.16.x / 3.22
