### ISSUE TITLE
Visualist doesn't load

### ISSUE THREAD

**Issue by keboen** [esc-unil/Visualist#3]
An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type PointsInPolygon has been deleted 
Traceback (most recent call last):
  File "C:/Users/bobco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\visualist\visualist_provider.py", line 85, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type PointsInPolygon has been deleted

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.1-Zanzibar Zanzibar, dcd95cc648

**Comment by qrossy** [comment]
Bug fixed, I'll push a new version ASAP
