### ISSUE TITLE
Chroropleth map: weight field doesn't work

### ISSUE THREAD

**Issue by lluisvicens** [esc-unil/Visualist#5]
I've been testing Visualist plugin for education purposes, and I've realized that **_Weight field_** on choropleth maps, doesn't work properly.

No matter if I select or not a numeric **[Population]** field on weight field parameter when I create a Choropleth map, the final result it's always the same (in terms of NUMPOINTS and the appearance of the classification map).

Any hint?

**Comment by qrossy** [comment]
Thank you for the information, I will check that and give you a feedback.

 

 

De : Lluís <notifications@github.com> 
Envoyé : jeudi, 19 mars 2020 12:46
À : esc-unil/Visualist <Visualist@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [esc-unil/Visualist] Chroropleth map: weight field doesn't work (#5)

 

I've been testing Visualist plugin for education purposes, and I've realized that Weight field on choropleth maps, doesn't work properly.

No matter if I select or not a numeric [Population] field on weight field parameter when I create a Choropleth map, the final result it's always the same (in terms of NUMPOINTS and the appearance of the classification map).

Any hint?

**Comment by qrossy** [comment]
I'll try to make an update, but you just have to use the field NUMPOINTS_WEIGHTED 
Layer properties > Symoblogy > Value : set NUMPOINTS_WEIGHTED

**Comment by qrossy** [comment]
Bug fixed, I'll will push a new version ASAP

**Comment by lluisvicens** [comment]
> Bug fixed, I'll will push a new version ASAP

Cool. Thanks!
