### ISSUE TITLE
Error to instal on QGIS 3.14

### ISSUE THREAD

**Issue by bellanz80** [esc-unil/Visualist#6]
hi. I have the following error:
I install it without problem, it loads in the processing panel.
But, if I enter the QGIS options menu, when clicking the "ok" button, a python error appears, and the plug disappears in the processing menu.
windows 10
QGIS 3.14.1

An error has occurred while executing Python code: 

RuntimeError: wrapped C/C++ object of type PointsInPolygon has been deleted 
Traceback (most recent call last):
  File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\visualist_provider.py", line 85, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type PointsInPolygon has been deleted

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.1-Pi Pi, de08d6b71d 

![image](https://user-images.githubusercontent.com/38449926/88703768-c381e180-d0d2-11ea-97f8-e012a3d4e8d5.png)

**Comment by qrossy** [comment]
Thank you for the feedback. I’ll have to check with the new version of qGis.

 

De : bellanz80 <notifications@github.com> 
Envoyé : mardi, 28 juillet 2020 20:05
À : esc-unil/Visualist <Visualist@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [esc-unil/Visualist] Error to instal on QGIS 3.14 (#6)

 

hi. I have the following error:
I install it without problem, it loads in the processing panel.
But, if I enter the QGIS options menu, when clicking the "ok" button, a python error appears, and the plug disappears in the processing menu.
windows 10
QGIS 3.14.1

An error has occurred while executing Python code:

RuntimeError: wrapped C/C++ object of type PointsInPolygon has been deleted
Traceback (most recent call last):
File "C:/Users/Luca/AppData/Roaming/QGIS/QGIS3\profiles\LUCA1/python/plugins\visualist\visualist_provider.py", line 85, in loadAlgorithms
self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type PointsInPolygon has been deleted

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
QGIS version: 3.14.1-Pi Pi, de08d6b71d

 <https://user-images.githubusercontent.com/38449926/88703768-c381e180-d0d2-11ea-97f8-e012a3d4e8d5.png>

**Comment by qrossy** [comment]
Bug fixed, I'll push a new version ASAP

**Comment by bellanz80** [comment]
Very thank's!!!
